name: Pull Request Auto Version Update
on:
  pull_request:
    branches: [main]
permissions:
  contents: write

jobs:
  Create-and-update-version:
    name: Create and Update Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: npm help

      - name: Install dependencies
        run: npm i -g conventional-changelog-cli conventional-recommended-bump

      - name: Determine new version
        run: |
          export NEW_VERSION=$(conventional-changelog -p conventional-recommended-bump -i CHANGELOG.md -s)

      - name: Update package.json
        run: npm version ${NEW_VERSION}

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'chore(version): update version ${NEW_VERSION}'
          git push
