on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          package-name: standard-version
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/checkout@v3
      - run: |
           npm config set //npm.pkg.github.com/:_authToken $GITHUB_NPM_AUTH_TOKEN
           npm install
           npm run build
           npm publish
        env:
           GITHUB_NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}

